( * GLS grammar using EBNF metasyntax * )

( *
symbol table = "symbol table { ",
         whitespace, { symbol, whitespace, ",", whitespace }, ";", 
         " }" ;
* )

axiom = "axiom"
         whitespace, string, ";" ;

production = "productions { "
        { whitespace, ":", whitespace, symbol, whitespace, "( ", { letter, condition, number }, " )", whitespace, ":=", string, ";" } ;

string = symbol, whitespace, { symbol, whitespace } ;
symbol = letter, { letter }, "( ", { letter, [arithmetic operator, number] | number, "," }, letter, [arithmetic operator, number] | number, " )" ;
condition = "<" | ">" | "<=" | ">=" | "=" | "!=" ;
number = ["-"], digit not zero, { digit }, [".", { digit }] ;
( * operator = ";" | "( " | " )" | ":=" ; * )

letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;

digit = digit not zero | "0" ;
digit not zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

whitespace = { " " } ;
